import { NextResponse } from "next/server";
import { AUTH_ROUTES } from "@/src/lib/authFlow";
import { getSupabaseServerClient } from "@/src/lib/supabaseServer";

export async function POST(req: Request) {
  try {
    const { email, type } = await req.json();

    if (!email) {
      return NextResponse.json(
        { success: false, message: "Email is required." },
        { status: 400 }
      );
    }

    const supabase = getSupabaseServerClient();
    const cleanEmail = String(email).trim().toLowerCase();
    const origin =
      req.headers.get("origin") ??
      process.env.NEXT_PUBLIC_SITE_URL ??
      "http://localhost:3000";

    const error =
      type === "recovery"
        ? (
            await supabase.auth.resetPasswordForEmail(cleanEmail, {
              redirectTo: `${origin}/Setnew_Password`,
            })  
          ).error
        : type === "login"
          ? (
              await supabase.auth.signInWithOtp({
                email: cleanEmail,
                options: {
                  shouldCreateUser: false,
                  emailRedirectTo: `${origin}${AUTH_ROUTES.otpVerify}?email=${encodeURIComponent(cleanEmail)}&type=login`,
                },
              })
            ).error
        : (
            // This route only asks Supabase to resend the email OTP.
            // The OTP length/format is generated by Supabase, not controlled here.
            await supabase.auth.signInWithOtp({
              email: cleanEmail,
              options: {
                shouldCreateUser: true,
                emailRedirectTo: `${origin}${AUTH_ROUTES.otpVerify}?email=${encodeURIComponent(cleanEmail)}&type=signup`,
              },
            })
          ).error;

    if (error) {
      return NextResponse.json({ success: false, message: error.message }, { status: 400 });
    }

    return NextResponse.json({
      success: true,
      message:
        type === "recovery"
          ? `Reset instructions have been sent to ${cleanEmail}.`
          : type === "login"
            ? `A new sign-in code has been sent to ${cleanEmail}.`
          : `A new OTP has been sent to ${cleanEmail}.`,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unable to resend OTP.";
    return NextResponse.json({ success: false, message }, { status: 500 });
  }
}
